### ISSUE TITLE
Default tag rules are re-added after restart, even after deletion

### ISSUE THREAD

**Issue by wklimowicz** [windingwind/zotero-tag#110]
The 2 default rules (removing and adding `/unread` tags on open and close) are applied upon relaunching Zotero, not just upon installing the plugin.

Steps to reproduce:
1. Delete the default rules
2. Reboot Zotero
3. Rules re-appear.

**Comment by RitaQian-westlake** [comment]
I haven't tried to remove default rules but found something similar. 
If I reboot Zotero and open Preference, **Actions** would only display the first three rules (2 default and the one I added at the most beginning). Other added rules remain vanishing unless I click the rule plus button.

**Comment by qiqi23278** [comment]
是的，我也有这样的问题，删除了默认规则，添加了4个新规则，重启后只显示前3个新规则，点击+号后，第4个新规则和原来删除的规则都出现了。zotero7 beta39+tag 1.0.0-3
