### ISSUE TITLE
大神能否实现在某一信息字段里面快捷键添加标签呢

### ISSUE THREAD

**Issue by mrsunhuang** [windingwind/zotero-tag#12]
目前添加标签实现不了排序，如果在某一信息字段里面快捷键添加标签，可以很好的归类，谢谢

**Comment by windingwind** [comment]
在已有的字段里添加信息将会破坏文献的原始数据，尽管很多字段并不会影响引用，我仍然不太支持这种做法；添加新的字段将在未安装该插件的设备上引起各种未知问题。

我不太理解你的需求点，并且不太清楚你的需求和这个插件的关系：这个插件的标签特指zotero的tag功能。

1. 你希望根据日期、姓名等排序，已有条目包含这些信息并支持排序；
2. 你希望根据自定义的方式排序。排序的最终目的是筛选，而标签的直接作用就是筛选。我不认为真的有人会需要比较两个文献在某一方面的优劣，1-5星的标签+自定义其他标签已经解决了大多数筛选需要。

**Comment by windingwind** [comment]
并且，标签和字段是两个完全独立的东西，没法像你所说在字段里面加标签
