### ISSUE TITLE
tag里面设置没有了

### ISSUE THREAD

**Issue by BMXDa** [windingwind/zotero-tag#13]
今天打开tag设置，发现里面都没有了，但是以前设置的还能用。
![image](https://user-images.githubusercontent.com/101966143/162676303-a477e0bf-04a2-4781-8e61-75f46e203b03.png)

**Comment by windingwind** [comment]
前段时间有过一次版本更新。请试下这个操作：
菜单栏 工具->开发者->Run Javascript，在窗口左侧输入：`Zotero.Prefs.get("zoterotag.rules")`，点击Run，复制右侧的显示看下

![image](https://user-images.githubusercontent.com/33902321/162677664-4c8a78bb-a2e4-4714-96da-032c03caecb2.png)

**Comment by BMXDa** [comment]
[{"id":1,"tags":["/unread"],"autoadd":true,"autoremove":true,"group":"4"},{"id":2,"tags":["⭐"],"autoadd":false,"autoremove":false,"group":"1"},{"id":3,"tags":["⭐⭐"],"autoadd":false,"autoremove":false,"group":"2"},{"id":4,"tags":["⭐⭐⭐"],"autoadd":false,"autoremove":false,"group":"3"}]

**Comment by windingwind** [comment]
看起来不是tag插件的问题。你使用了其他什么插件，估计是有冲突
