### ISSUE TITLE
[Suggest]-Is it possible to add tags for each annotations in the pdf reader?

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-tag#14]
**[Suggest]** -Is it possible to add tags for each annotations in the pdf reader?
I think this shortcut key is very necessary for people who want to differentiate and mark each annotation!
Thanks!
可以实现在pdf阅读器内对每一条注释添加标签吗？我认为这个快捷键对想区分标记每一条注释的人来说非常有必要！！！非常感谢！
![图片](https://user-images.githubusercontent.com/57334649/163132169-32f2d484-c643-43da-9ba8-936457105416.png)
***
[https://www.zotero.org/support/note_templates](url)
`extensions.zotero.annotations.noteTemplates.highlight` can be modified of `{{if tags}} #{{tags join=' #'}}{{endif}}`
then the annotation can add the #tags.

**Comment by windingwind** [comment]
Do you mean you want to add tags to annotation with a shortcut?

**Comment by lil-i321** [comment]
yes

**Comment by windingwind** [comment]
Got it. I'll let you know when this feature is ready.

**Comment by lil-i321** [comment]
Add tags at the annotation locations in the pdf reader with short cut.

**Comment by windingwind** [comment]
@lil-i321 try v0.2.1

**Comment by lil-i321** [comment]
> @lil-i321 try v0.2.1
Thank you very much! Really fast response！
The new features are as good as the previous ones!
