### ISSUE TITLE
可以增加一个remove af item closed的动作吗？

### ISSUE THREAD

**Issue by Bryan1999-2100** [windingwind/zotero-tag#15]
目前的想法是文献添加后自动添加一个unread的标签；文献被打开后自动移除unread标签，同时自动添加on-reading的标签；文献阅读完成，关闭之后自动移除on-reading的标签。

**Comment by windingwind** [comment]
后续更新。另外如果不使用自带阅读器，或者在独立窗口中打开，都无法触发关闭item事件。

**Comment by Bryan1999-2100** [comment]
感谢大佬🙏 期待后续更新。为了方便省事，更新6.0之后就只用自带阅读器阅读了😂

**Comment by windingwind** [comment]
已更新该功能
