### ISSUE TITLE
In my zeotero-tag, I can't find auto_tag

### ISSUE THREAD

**Issue by lx12633036** [windingwind/zotero-tag#18]

**Comment by windingwind** [comment]
Edit->Preferences->Zotero Tag
The 'auto-tag' was replaced by a more powerful 'actions' in the new version.
![image](https://user-images.githubusercontent.com/33902321/168207210-5a243135-b77e-4eb4-bbc6-48ff44c8dcc3.png)

The 'add on item add' is the so-called auto-tag in older versions.

**Comment by lx12633036** [comment]
> Edit->Preferences->Zotero Tag The 'auto-tag' was replaced by a more powerful 'actions' in the new version. ![image](https://user-images.githubusercontent.com/33902321/168207210-5a243135-b77e-4eb4-bbc6-48ff44c8dcc3.png)
> 
> The 'add on item add' is the so-called auto-tag in older versions.

When I restart Zetro,the actions will be change to disabled

**Comment by windingwind** [comment]
click ✅to apply changes

**Comment by lx12633036** [comment]
![3a183d61862d3c303f5bb4ae34a382e](https://user-images.githubusercontent.com/40138154/168213340-7da6a0f6-e98e-48cf-8df9-07bd16d06d9b.jpg)
I have click✅
