### ISSUE TITLE
您好，有些问题

### ISSUE THREAD

**Issue by lx12633036** [windingwind/zotero-tag#19]
1.我的一台电脑上会出现插件按照您的设置后，再次重启恢复默认（我估计是和其他插件冲突了？）
2.另外一台电脑，按照您的设置，无法获取/unread标签。前面也没有任何颜色标识。请问这个颜色标识是MAC版本才有？

**Comment by windingwind** [comment]
@roycham 
看起来这是因为青柠学术插件的早期版本使用了本插件的代码，并且没有做相应的修改，导致冲突。我不清楚是否现版本的青柠插件还会有该问题。
你可以尝试更新青柠到新版本，或者使用替代插件，如https://github.com/redleafnew/zotero-updateifs

**Comment by windingwind** [comment]
别客气。我将会关闭这个issue，有需要可以再打开。
