### ISSUE TITLE
Feature request: New interface to show tags inside Zotero main window

### ISSUE THREAD

**Issue by woodwm** [windingwind/zotero-tag#20]
Hi,

When there are few hundred items in a collection, it is usually difficult to find a specific one. One reason is that Zotero does not show tags for each item in the center window but only show those in the right window and left low window. 

A good practice is the issue board in github. See the issues in Rust repository https://github.com/rust-lang/rust/issues.
![image](https://user-images.githubusercontent.com/13971199/168426282-d0b40844-5002-429d-883d-7d786289267d.png)

It is more clear than Zotero.

So I want to request a feature to show tags along the item like github issue. Something like the below. The item height is enlarged to show the new tags there. 

![image](https://user-images.githubusercontent.com/13971199/168427085-3cf398eb-1249-4133-a7ad-a2089c41f5c8.png)

**Comment by windingwind** [comment]
An essential reason that the Github issues page with colored tags is clear is that its tag number is limited, no more than 5 for each issue and less than 20 in total.

However, in Zotero, an item may have more than 20 tags(including the auto-generated ones) and as you said, hundreds of tags in total. Which makes it impossible to present the tags in the Github way.

**Comment by woodwm** [comment]
I usually turned off the automatic tag in zotero as it makes tags less useful for me. Zotero can hide automatic tags as well.

If the height is enlarged, there is a full row to show tags. I normally do not have too many tags for each item, so I think it should be enough.

Could you show me an example of you reference that has more than 20 tags added by you excluding automatic tags?

**Comment by woodwm** [comment]
By the way, where do you find the limited of labels for issues in GitHub? 

I think it is not right. I can easily add more than 20 labels to a issue.

![3D3CFEBF-4E15-4301-8B55-7A81025C3B0E](https://user-images.githubusercontent.com/13971199/168464261-ba746269-f22f-48ba-945a-d885e5c0073d.jpeg)

**Comment by windingwind** [comment]
Sorry for my misrepresentation.

I mean in Github, usually, an issue won't have more than 5 tags. For the case you showed with 20 tags, the colorful tags are confusing and also unclear.

Zotero natively supports 9 colored tags, which will show up on the front of an item.

To implement this feature there is only a js injection way which would be ugly in both code and UI.

**Comment by woodwm** [comment]
As I said this is a extreme case that you have many colored tags for a item. Zotero do not allow you to have so many colored tags. Most tags are not colored and less disruptive. 

Anyway, if you think this is not a good idea and not interested, feel free to lose it.

**Comment by windingwind** [comment]
It's just a trade-off between the difficulty to realize and the benefit we could get. I don't have much time for all these issues.

Thanks for your suggestion anyway.
