### ISSUE TITLE
zotero移动到回收站的文献条目不会显示删除时间

### ISSUE THREAD

**Issue by Xieleilab** [windingwind/zotero-tag#23]
开发者您好！，非常感谢您开发的众多zotero插件，我发现目前zotero移动到回收站的文献条目不会显示删除时间，因此如果误删了某些条目，同时回收站已经储存了很多条目的话再想恢复就找不到了，请问您能开发一个插件显示回收站内的删除时间吗？谢谢您！（因为找不到您的联系方式所以在此回复了，请见谅！）

**Comment by windingwind** [comment]
这可能比较困难，删除时间并不存储在内部数据库
