### ISSUE TITLE
Not friendly to Mac OS

### ISSUE THREAD

**Issue by ChrisChoi1305** [windingwind/zotero-tag#24]
The shortcut is defined as Alt+Number. Could you please add some other options in the shortcut list? Thanks so much!
plus: the cmd+number is occupied

**Comment by windingwind** [comment]
Hi, sorry for my late reply.
Any suggestion about the shortcuts?

**Comment by kerim** [comment]
OK, now that I can add and save rules on the Mac, I'm running into this problem as well. Usually "alt" on Windows maps to "option" on Mac? 

https://www.lifewire.com/what-are-windows-keyboard-equivalents-to-mac-2260203

I see option and alt + number is taken up in Zotero by the PDF reader, but they should both be free when looking at the library?

https://www.zotero.org/support/kb/keyboard_shortcuts

**Comment by windingwind** [comment]
I'll update the shortcut part in the next release.
Would `ctrl + shift + number` and `ctrl + alt + number` be a good solution? ctrl is cmd and alt is option on mac.

**Comment by kerim** [comment]
Just to clarify, I think alt/option+number should be OK? They are currently only used by Zotero when in the PDF reader mode? Similarly, ctl + shift + number and ctl + alt + number seem to be used in the note editor, but it should be OK if one is not in that mode? If alt/option+number works without conflict I'd recommend keeping it at that - but I'm just not 100% certain how it works...

**Comment by windingwind** [comment]
Do the shortcuts work on Mac? The alt should be mapped to the option I guess. If they still doesesn't work, maybe there are conflicts between addons?

**Comment by kerim** [comment]
Sorry, the last 4 days have been chaotic. I'll try to test this out.

**Comment by kerim** [comment]
It seems like option+number is now working on the Mac, as I get a pop-up dialog telling me "success" - however the result is not as expected. I will open a separate issue as I think the problem has nothing to do with the keyboard sequence (which seems to be working now).

**Comment by wangyu407** [comment]
I think the shortcuts such as Alt+1 and Ctrl+Alt+1 do not work on my MAC. Maybe the more shortcuts option from user defined would be better.

**Comment by windingwind** [comment]
I'm not sure why shortcuts on Mac are not working... Can't debug with Mac make it hard to solve the problem.

Having totally customized shortcuts could be more complicated. I'm a little busy recently...

**Comment by wangyu407** [comment]
Thank you ,actually that doesn't matter, because  dragging the item with mouse is convenient. 😃




| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 11/05/2022 23:32 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [windingwind/zotero-tag] Not friendly to Mac OS (Issue #24) |

I'm not sure why shortcuts on Mac are not working... Can't debug with Mac make it hard to solve the problem.

Having totally customized shortcuts could be more complicated. I'm a little busy recently...

**Comment by windingwind** [comment]
Some Mac users report that the `alt(option)+number` works as expected. Could you please check are there any other software or plugins might have hotkey conflictions?

On Mac, the corresponding key of `alt` is `option`.

**Comment by wangyu407** [comment]
Thanks for you reply. 
I have tried to test option + 1 (as default ) in other Apps but there were nothing special. I think you are right that there might be hotkey conflict in my MAC but I don’t know how to review all the hotkey of the Apps that I am using. I am trying to find some software to show this important information. 
If I get some new information of this issue, I will send you the details. 


| |
王玉
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 11/7/2022 20:17 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [windingwind/zotero-tag] Not friendly to Mac OS (Issue #24) |

Some Mac users report that the alt(option)+number works as expected. Could you please check are there any other software or plugins might have hotkey conflictions?

On Mac, the corresponding key of alt is option.
