### ISSUE TITLE
Spaces removed in right-click Add tags option.

### ISSUE THREAD

**Issue by stanleyrhodes** [windingwind/zotero-tag#25]
I have tags that have spaces, and in some cases are phrases with more than two spaces. The use case here is 
1. Selecting one or more Zotero items
2. Right-clicking and selecting the "Add tags..." option
3. Entering a tag or tags with spaces.

I have the newest version, 0.2.7, installed. I uninstalled an old version of this plugin, then restarted Zotero, then installed 0.2.7. and restarted Zotero again before testing.

I saw this remove-spaces behavior was an issue with a previous version related to rule-setting (https://github.com/windingwind/zotero-tag/issues/22), but in this case I'm just talking about very basic operations of adding tags to Zotero items in the main screen.

Let me know if I can provide any additional information. Thanks for making this add-on, Zotero needed it very badly.

**Comment by windingwind** [comment]
Thank you for the suggestion! I'll fix it in the next release.

**Comment by windingwind** [comment]
Fixed
