### ISSUE TITLE
When adding a tag to hundreds of items at once, most of the items will not be tagged when Zotero is reopened.

### ISSUE THREAD

**Issue by stanleyrhodes** [windingwind/zotero-tag#26]
Background: I am working with a collection of 11k Zotero items. These items were collected by using search terms, so they are split into folders with those search terms for names. There are folders with 1000 items and ones with only 30. I am using this Zotero plug-in to select all items in a directory and name them with a tag that indicates the search term. Since I cannot put spaces in the names currently (https://github.com/windingwind/zotero-tag/issues/25), I am using underscores.

Issue: When I select-all (ctrl+A) the items in a folder and use this plugin to add a tag, a box in the lower-right says "success add [tag] to [some number] items" (or something similar). If I click through the items, they all seem to have the tag. If I then close Zotero and open it, only the first few items (usually the first 20-33 items) have the tag. All the items after that do not have the tag.

If I do this process a few times, more items get tagged, and they're always at the top of the list. It seems like a process hasn't finished. But this is very strange considering they all appear tagged before I close Zotero. This even happens on folders with smaller numbers of items (e.g., 88 items, 243 items).

I found something odd that may (or may not) shed some light on this. If I select all items in a folder, add a tag to them, and, with the items still all selected, move the right-side scrollbar to the bottom (in the Zotero items pane), the scrollbar and view will begin to move back up on its own. Once I can move the scrollbar to the bottom, and NOT have the view move, the tags will "stick" and be there when I restart Zotero. This seems to suggest that some process has finished with the selected items in the Zotero pane.

**Comment by windingwind** [comment]
I'll see what's happening to the items when tagging. Thanks for the report!

**Comment by windingwind** [comment]
Please try v0.2.8. I tested on 200+ items and the tags should be displayed one by one. Please wait until the bottom-right box shows up and do not exit Zotero during processing.

**Comment by stanleyrhodes** [comment]
Great! I've tested it, and it works. I do wonder if there's a way to make it faster, but that's a minor inconvenience. Most people will not be using it on the scale that I do.

Unless a user were to read this thread before using, they wouldn't have any idea what's going on between initiating the tagging and the success window. Even with only ~500 tags, it takes a minute or more. I'll make a feature request for improving the UX a little in this regard.

Thanks very much for fixing this! This plug-in has been a huge help to me.
