### ISSUE TITLE
无法添加标签

### ISSUE THREAD

**Issue by xinzaizi** [windingwind/zotero-tag#27]
您好，
非常感谢您给大家提供这么好的插件，但是目前我遇到了问题。

在使用的过程中，我想自定义tag,但是我在首选项-Zotero-tag中自定义标签时，无法保存，恢复默认设置。

希望您能提供给我一些建议，谢谢。

**Comment by windingwind** [comment]
请检查：
1. 是否安装了zotero-if插件。由于其使用了本插件的部分代码且似乎长期以来存在冲突，建议关闭其中一个
2. 编辑标签组后请按右侧对勾按钮来保存
