### ISSUE TITLE
Remove one tag on assigning another tag

### ISSUE THREAD

**Issue by kerim** [windingwind/zotero-tag#28]
I have several tags to help me sort and prioritize my reading, such as "important" and "to read" - I'd like these automatically removed when I add the tag "done" (thanks to you I've replaced these with emoji: ⭐️,  📌, ✅). And with the keyboard it would be great if I could toggle between all three tags, so that first one appears, then the other, then the other.

**Comment by windingwind** [comment]
Please update and use the prefix `~~` before the tags in the rules to mark them as to be removed.

Like this:
![image](https://user-images.githubusercontent.com/33902321/179448889-151bacd1-d07a-41c6-a132-5acc3947ed3b.png)

The `⭐️` tag will be added/removed when the shortcut/auto event is triggered and the `1` & `/unread` will be removed.

**Comment by kerim** [comment]
Thanks.

**Comment by kerim** [comment]
Now that the keyboard commands are working the Mac, I am able to test this. I have the following rule: `✅,~~⭐️` but when I invoke its with the keyboard it only adds ✅, it does not remove ⭐️, so I end up with both.

**Comment by windingwind** [comment]
That is strange, as it works fine on Windows. I don't think this add/remove tag function is platform-dependent, as this plugin has been used for several years.
I'll install a Mac VM to test the issues related to macOS. Thanks for reporting the bugs!

**Comment by paraselen** [comment]
same issue here. any fix?

**Comment by windingwind** [comment]
I have to admit running macOS in a VM is very slow, making it impossible to debug. If you are using macOS and encountered this bug, please do the following steps to help me debug:
1. Enable zotero-tag and disable other plugins;
2. Open Help-Debug Output-View Output
3. Show me the tag settings page;
4. Try to trigger one rule which contains ~~;
5. Upload the debug data here.

Thanks!
