### ISSUE TITLE
Batch remove rarely used tags

### ISSUE THREAD

**Issue by kerim** [windingwind/zotero-tag#29]
This request is a little different from what this plugin already does, but it is tag related so maybe you would consider it? 

I have many tags that are only used once or twice, and I would like to remove them - or even better (is there some way to do this) have them listed as "automatic tags" rather than regular tags, so that Zotero can hide them. 

The problem is that a lot of them are "automatic tags" but from another app I used before Zotero, so they are treated the same as regular tags. 

The way it would work is that the plugin would identify all tags that are only used 1,2, or 3 times and either remove them entirely, or change them into "automatic tags"

**Comment by windingwind** [comment]
A little difficult because knowing which tag is rarely used would require a full-database search. Too heavy maybe.
Maybe a 'remove all tags' will be helpful?

**Comment by kerim** [comment]
Well, I don't want to remove the tags I actually use! But the problem is that they are only a small percentage of my overall tags. The ones I do use will all be on at least 3 or more documents, while many of the others only appear once or twice.

**Comment by windingwind** [comment]
Maybe a right-click menu 'remove rarely used tags' and auto-count the tags under the current collection?
The rarely used tags would be the default value of the popup's input area, split with ','

**Comment by kerim** [comment]
Oh, thanks for continuing to think about this. I suppose it would be a two step process - first one needs to have the count and a list of the rarely used tags, then a way to batch remove them. Other than that, I don't have any particular insight into how it would work.

**Comment by windingwind** [comment]
Please try v0.2.13.
![image](https://user-images.githubusercontent.com/33902321/180808221-f37d5c3b-2e50-45bb-8de8-6bdf40612dee.png)

**Comment by kerim** [comment]
Is it possible to have the "check unused tags" feature ignore "automatic tags"? There is no need to remove those since they can be ignored. 

Also, since the list this produces is quite long, what I do is copy and paste the resulting list into a text file to inspect. Perhaps it would make sense to simply have the "check unused tags" produce a plain text file that is saved to the desktop? This also reduces risk of accidentally removing all the tags - since the user will probably want to keep some of them and so needs to edit the list before doing the "remove" operation.

**Comment by windingwind** [comment]
Maybe copy to clipboard would be a good solution?

**Comment by kerim** [comment]
That could work too.

**Comment by windingwind** [comment]
please try the latest
