### ISSUE TITLE
Auto-tags not working

### ISSUE THREAD

**Issue by krillin666** [windingwind/zotero-tag#3]
Hello,

Congrats for the extension, first off.

I am having trouble with auto-tags. I've tested versions 0.07,0.06 and 0.05 and couldn't get an auto-tag with newly added items to my library.

I've tested this with the Zotero connector for Firefox and with manually adding the DOI in Zotero. I've also tested with tags from different groups and set all to auto-add but to no avail.

Thank you.

**Comment by windingwind** [comment]
Thanks for letting me know. I will try to fix this in the next update.

Although it works fine to me, I do find it a problem for some Zotero users. 

I'm still not sure why the addon doesn't work. Could you please provide more details to help me fix it?

**Comment by windingwind** [comment]
@krillin666 Please try the latest version 0.0.9, I hope it works for you.
https://github.com/windingwind/zotero-tag/releases/tag/v0.0.9

If this problem is already solved, I'll close this issue.

Thanks!

**Comment by krillin666** [comment]
> @krillin666 Please try the latest version 0.0.9, I hope it works for you.
> https://github.com/windingwind/zotero-tag/releases/tag/v0.0.9
> 
> If this problem is already solved, I'll close this issue.
> 
> Thanks!

Thank you so much for the (quick!) fix. I have tested it and it is indeed working fine now. 
This is addon is crucial to my workflow, thank you once again !
