### ISSUE TITLE
Add tag on annotation

### ISSUE THREAD

**Issue by kerim** [windingwind/zotero-tag#30]
Just as this add-on can add an "unread" tag to newly added items, it would be great if it could add a "has annotations" tag the first time you add an annotation to an item. Is that possible?

**Comment by windingwind** [comment]
The 'unread' is added for users to remove it later after they finished reading. However, unlike the item/files, the annotations do not have a 'close' event, which means users have to remove these tags by themselves. I wonder in what condition do you need this feature?

Currently, you could use the `alt+number` shortcuts to add/remove tags to selected annotations.

**Comment by kerim** [comment]
Perhaps I didn't explain this clearly. I read many documents but I only annotate some of them. I would like to be able to filter my library to see which items in my database have annotations. Currently I don't see any way to do this? I thought that maybe having an automatic tag for annotated documents going forward would at least partially help - even if it can't identify those that already have annotations from before.

**Comment by windingwind** [comment]
Maybe a new event 'add the tag on annotation create'? Work the same way as the unread tags.

**Comment by kerim** [comment]
That is what I was thinking - assuming it is possible.

**Comment by windingwind** [comment]
Please try the latest
![image](https://user-images.githubusercontent.com/33902321/188308786-6d63612d-276e-4756-8a40-92c6be6758c1.png)
