### ISSUE TITLE
Request: Notify that tagging is happening, then notify when finished.

### ISSUE THREAD

**Issue by stanleyrhodes** [windingwind/zotero-tag#31]
This feature request to improve UX is related to this issue: https://github.com/windingwind/zotero-tag/issues/26 .

Issue: When tagging (or removing tags) from a lot of items, once the user initiates the action, there's no feedback that anything is happening. It would be reasonable for a user to assume that everything happens almost instantly, even though this isn't true. 

Solution: Have a little notification message that says the tagging is happening. If you want to use the same message for both adding and removing, it would be something like "Tags being updated. For hundreds of tags this may take awhile. Please wait . . ." 

Then, as already happens, the "Success" notification would trigger on completion, making it clear the updating was finished.

A more front-and-center option would be having a progress bar, like the "Find Available PDFs" option currently does. I'm not sure that's worth the effort, although it would make the process more transparent.

**Comment by windingwind** [comment]
Planned. Thanks!

**Comment by windingwind** [comment]
Please try the latest version. Sorry for my late reply.
![image](https://user-images.githubusercontent.com/33902321/188307364-fb965ab8-293c-41b2-8631-1b8ca2e97b80.png)
![image](https://user-images.githubusercontent.com/33902321/188307365-ae6abbeb-e286-438d-95b7-f44cb9cc0a0a.png)
