### ISSUE TITLE
Request: Being able to choose user-added tags in addition to automatically-added tags

### ISSUE THREAD

**Issue by stanleyrhodes** [windingwind/zotero-tag#32]
Issue: This plugin should be able to do user-added tags in addition to automatically-added tags. Zotero has some filtering and searching options that work best with user-added tags. For example, in my use cases, I would have preferred that this zotero-tag plugin resulted in tags of type user-added tags, and not type automatically-added tags; for my use I want automatically-added tags to be ONLY those picked up from the journal article web page. Note that I do not use the "Rules" options that this plugin provides; my use case is different than the one that probably inspired this plugin, but is still a Zotero power-user use case where this plugin is super useful.

Solution (three revisions would be needed, I think): 
1. The on-item right-click "Add tags" and right-click "Remove tags" windows would need to include a checkbox for both system-added type and user-added type. If having both checked would cause an issue, they would need to be radio buttons.
2. The Zotero Tag tab in the preferences could have a subtab (in addition to "Rules" and "Help" that enabled the user to specify what the default selection type for the on-item right-click "Add tags" and right-click "Remove tags" windows. For example, if I set it to "user-added default" then when I right-clicked on an item and clicked "Add tags" the user-added type would be the default checkbox or radio button (but I could still change it in the window if I wished).
3. Including the type of tag in the Rules subtab of the Zotero Tag tab in preferences. I don't have a strong opinion on how to do this, but I know it may be challenging because there isn't much room to put the option, and the Zotero Preferences window cannot be resized! This may be another reason to move the menu to its own window, accessible from the Tools main menu option. The Zutilo plugin, for example, does this, and has a resizable window. Either way, this may be as simple as having a column in the rules that is "User-added?" with a checkmark box that would make the rule add tags of type user-added when checked, but otherwise default to type automatically-added.

**Comment by windingwind** [comment]
Seem like it's a little bit complex. I'll try!

**Comment by windingwind** [comment]
About the preference window issue: I currently maintain 4 addons, that's why I try to keep the settings in one place(the prefs window). Easy to maintain and easy for users to find the settings.

**Comment by windingwind** [comment]
Please try v0.2.13
