### ISSUE TITLE
Request: customize shortcuts due to mess up with zotero default shortcuts

### ISSUE THREAD

**Issue by Asynchro-Epool** [windingwind/zotero-tag#33]
In the Zotero recent [update](https://www.zotero.org/support/changelog#changes_in_6010_july_18_2022), it provide shortcuts to switch the pdf reviewer toolbar with keys `alt+1`~`alt+5`, so it mess up with tags' shortcuts. 

Please allow to customize the shortcuts for tagging.

**Comment by windingwind** [comment]
I've noticed this change in Zotero 0.6.10.
Planned. Thanks!

**Comment by windingwind** [comment]
Now support alt+number and ctrl+alt+number.
The 1-4 shortcuts will be disabled if you are in the PDF view.
