### ISSUE TITLE
README is unclear about tag rules

### ISSUE THREAD

**Issue by VladimirAlexiev** [windingwind/zotero-tag#37]
I find https://github.com/windingwind/zotero-tag#settings quite unclear when it comes to tag rules.
I think the builtin description is more clear:
![](https://user-images.githubusercontent.com/94808374/183123894-2926d185-9be4-4ccc-a119-b18335b89abc.png)

So: you have tag groups, and they are enacted with Alt-n (0..9); a group can add and/or remove tags

The README talks about "Actions for tag groups", which for me is confusing.

**Comment by windingwind** [comment]
Thanks for pointing out! I'll update the readme's settings part.
