### ISSUE TITLE
[Feature] tag cleanup (normalize/canonicalize tags)

### ISSUE THREAD

**Issue by VladimirAlexiev** [windingwind/zotero-tag#38]
We have hundreds of tags in https://www.zotero.org/groups/3007408/semantic_bim/items/PGZA3JEN. Many of these tags are duplicated. Reasons:
- Many of the tags came with item metadata, and many were added manually.
- Zotero's tag autocompletion helps a bit, but is not enough
- When I see a metadata tag "Building Information Modeling (BIM)", I split it to "Building Information Modeling" and "BIM" to ensure findability through either. But these tags mean the same, so are are duplicates 

It's a group library with 20 members and will grow to 40. A lot more people will be entering tags.

Feature Request:
- Add function "Export tags" for a library (or collection). Optionally, include count of items per tag
- Add function "Normalize tags" that takes an normalization file like this:
```
BIM: building information modeling, Building Information Modeling (BIM)
ACC: automated compliance checking, automated code checking, automated compliance checking system
```
- then for every item: replaces any tag on the right side with the single tag on the left side

This would help our work immensely!
Thanks in advance!

**Comment by windingwind** [comment]
Hi,
I noticed you are also using or trying to use Better Notes plugin. Actually, the export and normalization can be achieved by its template function. Though that would be a little complicated, it's much faster and you could use it right away. If you want it as soon as possible, I could write a template to export and normalize tags.

Or, I can add these functions to this plugin if you are not in a hurry.

About export tags:
You can do it right now with this plugin, though without counts. It can be done with the right-click menu->add/remove tags->check rarely used tags->set the threshold to a very big number(999999) and you will get all tags under the current collection.

**Comment by VladimirAlexiev** [comment]
@windingwind You are my hero!
- I'll try export right away
- "template" is a piece of JS magic, right? If you could create one for this task, I'll be very grateful
  It'd still need a file like `tag: alias1, alias2, alias3` , right?

I'll talk to project partners to sponsor you. Which way do you prefer?
- https://liberapay.com/windingwind
- https://paypal.me/windingwind?country.x=C2&locale.x=zh_XC

**Comment by VladimirAlexiev** [comment]
https://github.com/windingwind/zotero-tag/issues/39

**Comment by windingwind** [comment]
> "template" is a piece of JS magic
Yes. If you are familiar with JS, it would be convenient to use the template to do repeating operations.

The input can be from a file or clipboard. Depending on how you design it.

Thanks in previous! If you want your name to show up in the sponsor history, then Librapay; otherwise using PayPal directly would be more convenient maybe.

**Comment by windingwind** [comment]
Please try v0.2.18

![image](https://user-images.githubusercontent.com/33902321/193441592-af8ab160-85a6-41d2-9692-ec6b18937366.png)

See https://github.com/windingwind/zotero-tag#manage-tags-manually for how to use the export an import.
I'm not sure if there are any possible bugs with the import. Please create a playground collection/group and test it there in order not to spoil you data.

**Comment by VladimirAlexiev** [comment]
Thanks! I'll try it on Friday.
Zotero also has https://www.zotero.org/support/collections_and_tags#bulk_editing_tags: you can rename a tag in all items, but you have to do it tag by tag. Eg I just renamed maybe 15 different variations of "automated compliance checking" to "ACC".
