### ISSUE TITLE
add "check rarely used tags" and "export tags" on library, collection, subcollection

### ISSUE THREAD

**Issue by VladimirAlexiev** [windingwind/zotero-tag#39]
@windingwind 
> You can export tags right now with this plugin, though without counts. It can be done with the right-click menu->add/remove tags->check rarely used tags->set the threshold to a very big number(999999) and you will get all tags under the current collection.

But I want all tags in the current library. 
(I use collections and subcollections as "folders", reflecting the "main topic" of the items within

Steps:
- click on the shared library
- rclick on the first item inside
- try "check rarely used tags" 
```
[JavaScript Error: "TypeError: ZoteroPane.getSelectedCollection(...) is undefined" {file: "chrome://zoterotag/content/scripts/index.js" line: 588}]
doUpdate@chrome://zoterotag/content/scripts/index.js:588:11
oncommand@chrome://zoterotag/content/manual.xul:1:1
```

Furthermore, this function is kind of hidden since it doesn't pertain to a single item.

So could you please:
- add a context item "check rarely used tags" on Library, Collection and Subcollection 
- add a context item "export tags" on Library, Collection and Subcollection
- if possible, add an option to download them as newline-separated, rather than having to copy them out of a tiny edit box

Cheers!

**Comment by windingwind** [comment]
Seem like this is a bug. I'll fix it soon. Thanks for letting me know!

I will add the export & update funciton to the next release.😁

**Comment by windingwind** [comment]
Done
