### ISSUE TITLE
无法添加星号？

### ISSUE THREAD

**Issue by 664787022** [windingwind/zotero-tag#40]
[item-star.md](https://github.com/windingwind/zotero-tag/commit/d7581b634cc4f7bba0c6e6a64f39bb0a68f5676c) 这个文档里写的是输入⭐添加星号标志。 但是我输入了以后并没在条目里显示⭐
![](https://img-blog.csdnimg.cn/e13dae83fe444225b58eb356d271df8f.png)
![](https://img-blog.csdnimg.cn/577d52b659284a7885555304b1fe1e7c.png)

是不是我输入⭐的字符不对呀？我是从[item-star.md](https://github.com/windingwind/zotero-tag/commit/d7581b634cc4f7bba0c6e6a64f39bb0a68f5676c) 的 raw text 里复制的⭐。 ⭐要怎么打出来？
![](https://img-blog.csdnimg.cn/f01825e8d8ff429d8023b01942cc1ca8.png)

**Comment by 664787022** [comment]
知道了知道了！编号要与星号数量相同

**Comment by wzh4464** [comment]
怎么加星号呀，解决了嘛？

**Comment by windingwind** [comment]
需要给标签分配颜色。请仔细阅读文档
