### ISSUE TITLE
想问一下add on item annotation add是什么意思，干什么的

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-tag#41]
想问一下add on item annotation add是什么意思，干什么的，我以为是给pdf旁边的annotation，每个批注单独批量加标签的，但好像无法实现这个功能。

**Comment by windingwind** [comment]
在新增批注时为他们设置标签，类似add on item add。

有什么更加简洁清晰的表述方法吗？

**Comment by windingwind** [comment]
为批注添加标签可设置快捷键后，选中批注使用快捷键添加。
alt1-4被阅读器占用，选择其他快捷键即可。
