### ISSUE TITLE
导入标签功能与预期不符

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-tag#44]
我根据下面的说明，打算通过导入标签（-）来批量删除一些条目中的标签
> +,/unread,/new
> -,toremove,
> =,BIM,building information modeling,Building Information Modeling (BIM)
> =,this is comma($COMMA$),$COMMA$

但是，我发现**减号（-）似乎并不能删除标签，而是添加标签**

标签内容如下图
![Snipaste_2022-11-01_23-35-03](https://user-images.githubusercontent.com/22871049/199273406-75e6fbf9-ef77-4387-aaa7-8b3eb45b7659.png)
CSV文件内容
![Snipaste_2022-11-01_23-35-31](https://user-images.githubusercontent.com/22871049/199273571-7ea790c0-2b2a-4eb3-8c11-8bcbe9f6b0f4.png)
执行导入标签csv后，log显示如下
![Snipaste_2022-11-01_23-37-30](https://user-images.githubusercontent.com/22871049/199273980-2ea37e43-f427-4b97-acb8-d45ad73959b2.png)
删除该标签后，再次执行导入导入这个csv，会继续添加这个标签
![Snipaste_2022-11-01_23-46-09](https://user-images.githubusercontent.com/22871049/199276432-11714348-c2ca-49e4-a802-07dd0b5f1cbe.png)

**不知道是我操作的问题还是插件的bug？**

**zotero**：6.0.17-beta.1
**zotero-tag**：0.2.18
**OS**：Win11 22H2

**Comment by windingwind** [comment]
sorry，是bug。将下一次更新修复。
