### ISSUE TITLE
Add tags based on currently added tags

### ISSUE THREAD

**Issue by jrwrigh** [windingwind/zotero-tag#45]
I'd like to have a hierarchy of tags for my articles, but have them be somewhat automatically set. I am thinking of something similar to GMails Filter tagging system. Say I have the desired hierarchy:

```
1. Finite Elements
  1.1 Stabilization
    1.1.1 SUPG
    1.1.2 VMS
    1.1.3 GLS
  1.2 Continuous Galerkin
 ```
 
 So if I manually add a tag for `SUPG`, I'd like a plugin to automatically add `Stabilization` and `Finite Elements`. If I further manually add `Continuous Galerkin`, it should be able to notice that `Finite Elements` is already added and leave it alone.
 
 This might just be an extension of the "tag rules" that is currently implemented already. But it'd take the form of "if /stabilization is added, add /finite_elements"
 
 Note this rules-based application of tags would work fine (and maybe be preferable) as a manual activation. ie. I'd add the tags I care about, ie. `SUPG` and `Continuous Galerkin`, and then explicitly request the plugin to auto-add tags based on a set of rules I've already setup.

**Comment by windingwind** [comment]
Thanks for the interesting suggestion. I'll try to add it in the next release.

**Comment by windingwind** [comment]
Please try v0.3.0. I've updated the README.
