### ISSUE TITLE
Add tag on add note rule

### ISSUE THREAD

**Issue by ninh-bui** [windingwind/zotero-tag#46]
Hello, I tried setting up this automatic tag rule similar to the default 'unread' tag. I'm trying to make the plugin automatically add an annotated tag, whenever I "Add note from annotation". I thought that "Add tag on item annotation add" was for something similar, but I found out that it's not. Is it possible to have this feature in the future?

Feedback: The rule "Add tag on item annotation add" is kind a misleading. I think it should be named "Add tag on adding annotation" or "Add tag on new annotation".

**Comment by windingwind** [comment]
Thanks for your suggestion. I'll add it in the next release, with rule action names corrected.
