### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by rthu67** [windingwind/zotero-tag#47]
为什么我按Alt+1时不出现标签，而是界面的切换？

**Comment by windingwind** [comment]
alt键在mac平台是option键，不是cmd键

**Comment by rthu67** [comment]
那windows呢，我的它每次都冲突就。。。

**Comment by windingwind** [comment]
windows就是alt键。确认你不是按了ctrl键？

**Comment by rthu67** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/65283884/200521727-9cf50958-a658-4b08-b879-e5f67962b31a.png">
我按完Alt+2之后就是面板的切换，不是添加标签。。。。。

**Comment by windingwind** [comment]
这个截图我无法看出来任何内容。请确认没有其他插件冲突，并且你确实按的是alt，不是ctrl或者win键。https://zhidao.baidu.com/question/304950507.html

**Comment by rthu67** [comment]
就是正常打开以后，原本正常的zotero界面，快捷键alt+2时候就变成如图所示，添加不了标签（手动鼠标添加是可以的），而且我按键是正确的。。。不知道是不是快捷键冲突问题，，或者其他原因。

**Comment by domeZhao** [comment]
我也是这个问题，检查之后发现是别的软件快捷键冲突了，你可以看看是不是全局快捷键冲突。
