### ISSUE TITLE
添加标签后，文献名前并没有出现指派颜色标记

### ISSUE THREAD

**Issue by Estvanc** [windingwind/zotero-tag#49]
按照操作完成后，标签在左下角栏目已有，但是文献的名字前并没有出现如介绍中的指派颜色，想问是哪里操作有遗漏吗？
![ff3921782a0a46ecef6fbc8982e1a31](https://user-images.githubusercontent.com/40912747/200471590-28bffb80-6364-4755-9b18-c60b642347e1.jpg)

**Comment by windingwind** [comment]
文献是否具有这个标签

**Comment by Estvanc** [comment]
我是采用的对文章进行标注后自动添加readed标签，然后在文章中文本高亮，右下角也显示了 done的标识，点击左下角的/readed也会显示这边文章。但是没有您在展示中的直接文献前出现指定颜色的小正方形颜色块的标识。

**Comment by windingwind** [comment]
是否设置标签颜色

**Comment by Estvanc** [comment]
是在指派颜色后，还需要有操作吗？我这里已经给标签指派了颜色

**Comment by windingwind** [comment]
如果条目确实具有一个彩色标签而未在库中显示，那可能是zotero有某种设置或者问题导致彩色标签没有正常显示，可以向https://forums.zotero.org/discussions 提问，应该与插件无关
