### ISSUE TITLE
How to Extended label color？

### ISSUE THREAD

**Issue by foryond** [windingwind/zotero-tag#5]
Now, Zotero's Tags have only 9 colors at most, Can U extended the label color to as much as we can?
![tag-color-img-2](https://user-images.githubusercontent.com/45784147/159403946-06f4fca8-44f8-4615-a7b7-d02d45fd8150.png)

**Comment by windingwind** [comment]
Sorry, it is difined inside Zotero. I can do nothing with the limitation.

**Comment by foryond** [comment]
Thank you
