### ISSUE TITLE
更新后mac os不能更换设置

### ISSUE THREAD

**Issue by kohayao** [windingwind/zotero-tag#50]
如图所示，确定更改设置的✅键出现在界面之外，而首选项的界面框无法拉宽和左右移动
<img width="670" alt="image" src="https://user-images.githubusercontent.com/107913352/200840668-74f00766-3e3e-4c1e-8ff0-de3573c07212.png">

**Comment by windingwind** [comment]
感谢反馈，未来版本将取消确定键，自动保存。

**Comment by windingwind** [comment]
已修复

**Comment by kohayao** [comment]
感谢🙏
