### ISSUE TITLE
could not Rate Items with Star

### ISSUE THREAD

**Issue by yzliu01** [windingwind/zotero-tag#51]
Hi, I could not figure out how to rate items with stars following your instruction for Zotero tag add-ons, https://github.com/windingwind/zotero-tag/blob/master/docs/item-star.md#rate-items-with-star. How could you add a star symbol as a tag as you demonstrated there? Is it possible to check a star mark in front of the items, as that is for favorites in Mendeley? Also another function - Recently Read items, which I find useful. 
![image](https://user-images.githubusercontent.com/93487645/201167146-2e0c10e4-bf88-4df1-9b03-28fe794ed73b.png)
Thanks a lot beforehand.

**Comment by windingwind** [comment]
> How could you add a star symbol as a tag as you demonstrated there

Just copy the start ⭐ and paste it when you add tags.

**Comment by yzliu01** [comment]
Many thanks. Got it. That's fantastic!
