### ISSUE TITLE
【建议】解除对指派颜色标签的数量限制

### ISSUE THREAD

**Issue by BurgessX** [windingwind/zotero-tag#52]
依我看来，为标签指派颜色主要是为了让某些重要标签（比如顶级标签）在标签列表中置顶，且看起来更加醒目。现在这个插件限制了最多添加 9 个颜色标签，我估计是考虑到快捷键的数量不够。

然而对一部分人（包括我）而言，他们并不那么需要使用颜色标签的快捷键功能（手动输入一个标签似乎也不是很慢），对他们来说更重要的是利用颜色标签功能对不同层级或不同类别的标签进行分类，比如：

- 一级标签全部用红色，二级标签全部用橙色……
- 论文层级标题相关的标签用一种颜色，阅读状态相关的标签（比如 `/unread` 标签）用一种颜色，文献本身内容相关的标签用另一种颜色
- 等等

可能上述功能的实现会与现有功能冲突，但解决方法是有的，比如：

- 可以设置两种使用模式，一种是现有的「9 标签 + 快捷方式」的模式，另一种就是我提到的「无限数量颜色标签 + 无快捷方式」的模式
- 或者，可以不强制「一种颜色绑定一个快捷键」，而是「一个标签对应一个快捷键」，具体哪个标签要绑定快捷键可以由用户在设置面板中定义

以上，希望能采纳~

**Comment by windingwind** [comment]
这属于zotero功能，请向https://forums.zotero.org/discussions报告。
