### ISSUE TITLE
希望规则中可增加首次打开时添加标签或设置打开文献一段时间后添加标签

### ISSUE THREAD

**Issue by lz0709** [windingwind/zotero-tag#54]
我现在为区分是否阅读，设置当打开文献时自动添加阅读中的标签，但在部分情况下我只是打开里面某一个信息，约1分钟就会退出，且这篇文献之前已经完成阅读，但是此时会重新为其添加阅读中的标签，能劳烦作者添加这一项更多的触发方式，如某一标签存在时不触发此规则等。或您有什么好的设置方式，能麻烦提供给我。
I have now set up to automatically add an in-reading tag when opening a document in order to distinguish between reading and not reading, but in some cases I just open for a piece of information in it and  will exit soon,. but then the in-reading tag is added again for it 
 even the document has been read before, can you add a trigger for this or do you have any good settings that you could please provide me with?

**Comment by windingwind** [comment]
> 如某一标签存在时不触发此规则等

见#58 ，可在那边讨论
