### ISSUE TITLE
增加一列标题栏用于存放tag

### ISSUE THREAD

**Issue by xinyuzhangxy** [windingwind/zotero-tag#56]
最新版tag插件中，除颜色tag外，自定义的tag符号不能在标题中显示，需点击特定tag后才能看到对应tag合集。
如果标题栏可以增加一列，用于存放自定义的tag的话，一目了然，就完美了~

**Comment by MetrixLambert** [comment]
Same problem, hoping for fix

**Comment by txctxc** [comment]
> @xinyuzhangxy You can refer to this website for details.https://zhuanlan.zhihu.com/p/511129371
I hope this helps you.
