### ISSUE TITLE
0.3.0标签添加条件判断失败

### ISSUE THREAD

**Issue by lz0709** [windingwind/zotero-tag#59]
/reading[!/reading],~~/unread

**Comment by lz0709** [comment]
设置为此标签时候，希望在/reading不存在的时候添加/reading标签，但是实际上使用alt+2运行结果为添加了/reading[!/reading]标签，请问是何处设置错误了吗

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-tag#tag-rules

**Comment by windingwind** [comment]
`'/reading[!/reading]'`

**Comment by LamFTS** [comment]
我也是遇到类似的问题，直接将'/reading[!/reading]'变成了标签，没有起到判断的作用，不知道哪里出了问题。
![图片](https://user-images.githubusercontent.com/53118840/204126508-19fea092-b2c6-4424-8261-999ff0e0e36a.png)

**Comment by windingwind** [comment]
@LamFTS 请检查插件版本>=0.3.0

**Comment by LamFTS** [comment]
> @LamFTS 请检查插件版本>=0.3.0

升级到0.3.0版本后问题解决。

**Comment by xchyyb** [comment]
插件版本=0.3.0，仍然出现上述问题

**Comment by windingwind** [comment]
请具体描述，提供截图与调试输出；如果没有后续回应，将关闭问题

**Comment by renyuneyun** [comment]
提示：注意增加单引号。
我就是漏了这点。
或许可以在文档中强调一下？
