### ISSUE TITLE
I can't set the tags in zotero 6.0. 

### ISSUE THREAD

**Issue by PungTeng** [windingwind/zotero-tag#6]
![image](https://user-images.githubusercontent.com/48271804/161361161-b64c1b7c-540e-4f0b-b56c-c7f2894b3f54.png)

设备：macbook pro m1

右键之后没有看到快速标签之类的，即使输入/unread也没有标星，请问这是咋使用？

**Comment by windingwind** [comment]
输入unread当然是标unread🤣
在设置里可以设定标签组和快捷键，标星功能见https://github.com/windingwind/zotero-tag/blob/master/docs/item-star.md
