### ISSUE TITLE
跨设备同步时标签改变或消失

### ISSUE THREAD

**Issue by LamFTS** [windingwind/zotero-tag#61]
我在两台设备上安装了zotero，经常需要在两台设备之间切换，存在这样一个问题，比如，A设备上已经是`/readed`或`/open`的状态，但是在一同步到B设备，从A设备同步过来的条目在B设备就相当于新条目，就会触发执行`/unread`标签的指令，所以在A设设备上的`/readed`或`/open`标签会变成`/unread`/，有时候会直接消失。

**Comment by windingwind** [comment]
请参阅设置条件标签，即仅在没有`/readed`情况下添加`/unread`。

**Comment by LamFTS** [comment]
能不能实现多条件判断呢？即在没有`/readed`或没有`/open`的情况下添加`/unread`，如果只是在没有`/readed`的情况下自动添加`/unread`，当条目在A设备上是`/open`状态时，首次同步到B设备，仍然会被设置为`/unread`。

**Comment by happyTonakai** [comment]
添加两个规则试试？
`/unread[!/open]`
`~~/unread[/readed]`
