### ISSUE TITLE
Export tags does not include/map child-note tags?

### ISSUE THREAD

**Issue by sjgknight** [windingwind/zotero-tag#62]
In a collection, I have parent items each with child notes. The tags differ for the parent-item and child-notes and this mapping is important. 

I'm trying to map tags back to notes exported using your other great extension @windingwind https://github.com/windingwind/zotero-better-notes where I changed the `ExportMDFileName` template from `${noteItem.key}.md` to `${noteItem.id}-${noteItem.key}.md` so I could join to the tags.  But, I don't think the tag export is mapped at this level (it's slightly hard to tell because IDs aren't easily visible within zotero), is that right?

**Comment by sjgknight** [comment]
@windingwind that would be fantastic, yes! In my current case, I finally caved and just accessed the sqlite db table for tags and notes directly. I think this is two things:

1. In zotero-tag, the ID exported for each item is for the parent item, not the child. That means we cannot use this export to link the childnotes to the tags. 
2. In better-notes, the 'export to .md' function is not templatable, so these fields cannot be added to that export. As you say, adding the tags to the yaml header would be a great approach, but it may be more flexible/sustainable if it's possible to template this export.

**Comment by windingwind** [comment]
Template for yaml head would be definitely possible.

**Comment by sjgknight** [comment]
Thanks @windingwind just for sake of completeness for anyone else looking, that's the `[ExportMDFileHeader]` template within the Template Editor menu (under Zotero's edit menu) in the BetterNotes plugin.  It can be edited separately to the filename template. 
I just made one minor edit to the template to add under the item key under the title for efficiency. 
`  header.parentID = noteItem.parentItem? noteItem.parentItem.getField("key") : "";`

This has made working with the notes in external tools so much easier, thank you!
