### ISSUE TITLE
zotero6.0.18版本下，zotero-tag0.3.0无法自动添加unread标签及其他问题

### ISSUE THREAD

**Issue by fenshen000** [windingwind/zotero-tag#63]
### 在默认规则上修改和添加标签规则后，无法自动保存修改的设置；重新打开首选项时，tag设置界面只剩下`/unread`一个标签
- 修改好的标签规则：
   
![1](https://user-images.githubusercontent.com/43239563/206660366-11f5c961-a1ce-412d-9532-780316a0a254.png)
- 保存设置后点击OK关闭zotero首选项，再次重新打开首选项tag设置界面，设置会自动变成如下：
  
![2](https://user-images.githubusercontent.com/43239563/206660692-3778c9bf-e305-44b1-ac91-180717c4ecbb.png)
### 向zotero文献库中新增文献后，没有自动为它们加上`UnRead`标签
- 无论是默认的`/unread`还是我自己修改的`UnRead`标签，都没有自动添加上
### `add tags when creating note`实际上实现的是`add tag when creating annotation`的功能
- 在创建note（例如条目笔记）后，并不能触发`add tags when creating note`并添加相应标签；反而在创建注释后，`add tags when creating note`和`add tag when creating annotation`都会触发（显示于注释中）
  
![3](https://user-images.githubusercontent.com/43239563/206662606-bfa6b497-7cc6-44c6-a809-be08e48048ad.png)
- 无论是添加annotation还是note得到的标签（后者无法实现），都无法显示于文献的`标签`中：
![4](https://user-images.githubusercontent.com/43239563/206664263-9f9b850d-9fbc-4c9b-bd55-b6b0a3f03d51.png)

**Comment by windingwind** [comment]
- 设置被重置可能是zotero-if插件与此插件产生冲突。由于其不开源，我无法定位问题。
- 无法自动添加未读可能也与此有关

**Comment by onecorn065** [comment]
我也出现了这个问题，不过虽然首选项中会变成一个/unread，但使用快捷键可按照之前设置的进行正常操作

**Comment by fenshen000** [comment]
补充：
- 在遇到这些问题后第二天，插件自动恢复正常，不会自动重置也可以自动加上Unread标签，至今三个多星期时间里运行正常
- 并没有找到问题原因和解决方案，例如没有移除zotero-if插件；猜想是zotero自身或者某个插件进行了更新，避免了插件的冲突，发现此问题并找到具体解决方法的小伙伴欢迎进行补充。
- 插件里面`add tags when creating note`实现的仍然是`add tag when creating annotation`的功能，即文献中添加注释后才会显示`add tags when creating note`；直接对文献条目添加笔记，或者通过注释添加笔记再删除注释后，将无法触发`add tags when creating note`规则，不过感觉实现这一功能确实也挺难的。
- 辛苦作者大大了~

**Comment by ninh-bui** [comment]
I also see the same behavior of the rule `add tags when creating note`  described by fenshen000. Looking at this rule, I expect action  `Add note from Annotations` would trigger this rule and add tag to the corresponding item in the library, but it seems to be bugged?

**Comment by itshardforname** [comment]
我也遇到了你遇到的第一个问题，但是我实际使用的时候发现并不是像你描述的那样不会自动保存，他好像是前台显示和后台数据存储的一个bug，每次打开都有一个/unread的标签，但是随便新建一条规则之后，之前保存的标签规则就会再次出现，
并且/unread标签规则也会在添加新条目时自动添加，尽管已经删除掉了此规则

**Comment by fenshen000** [comment]
> 我也遇到了你遇到的第一个问题，但是我实际使用的时候发现并不是像你描述的那样不会自动保存，他好像是前台显示和后台数据存储的一个bug，每次打开都有一个/unread的标签，但是随便新建一条规则之后，之前保存的标签规则就会再次出现， 并且/unread标签规则也会在添加新条目时自动添加，尽管已经删除掉了此规则

可以像作者上面说的那样，假如安装zotero-if插件，试一试将那个插件卸载后再重新安装zotero-tag，可能就可以解决你遇到的问题，目前我还没遇到其他可能存在冲突的插件。
目前我的在zotero6.0.20版本下，zotero-tag是正常运行的，打开它的设置界面后可以直接看到我创建的规则，而不是`/unread`，也不会自动为新条目添加`/unread`标签：
![image](https://user-images.githubusercontent.com/43239563/220049226-06798046-4064-4977-a297-5901605ef3c0.png)
PS：
- `/unread标签规则也会在添加新条目时自动添加，尽管已经删除掉了此规则`这个问题***可能***是因为你在zotero-if设置中没有取消勾选这个选项。
- 实测在zotero新安装zotero-tag后遇到的一些小bug，假如不影响使用无视就好，会自己恢复正常，略为玄学...

**Comment by itshardforname** [comment]
> > 我也遇到了你遇到的第一个问题，但是我实际使用的时候发现并不是像你描述的那样不会自动保存，他好像是前台显示和后台数据存储的一个bug，每次打开都有一个/unread的标签，但是随便新建一条规则之后，之前保存的标签规则就会再次出现， 并且/unread标签规则也会在添加新条目时自动添加，尽管已经删除掉了此规则
> 
> 可以像作者上面说的那样，假如安装zotero-if插件，试一试将那个插件卸载后再重新安装zotero-tag，可能就可以解决你遇到的问题，目前我还没遇到其他可能存在冲突的插件。 目前我的在zotero6.0.20版本下，zotero-tag是正常运行的，打开它的设置界面后可以直接看到我创建的规则，而不是`/unread`，也不会自动为新条目添加`/unread`标签： ![image](https://user-images.githubusercontent.com/43239563/220049226-06798046-4064-4977-a297-5901605ef3c0.png) PS：
> 
> * `/unread标签规则也会在添加新条目时自动添加，尽管已经删除掉了此规则`这个问题_**可能**_是因为你在zotero-if设置中没有取消勾选这个选项。
> * 实测在zotero新安装zotero-tag后遇到的一些小bug，假如不影响使用无视就好，会自己恢复正常，略为玄学...

我直接禁用掉了zotero-if这个插件，因为他的功能和我现在用到的zotero-style有些功能重复，不过还是谢谢你

**Comment by jerryliu20d** [comment]
A dirty way to solve it: 1) disable zotero-if and restart, 2) set your preference for zotero-tag, restart 3) enable zotero-if, restart. And do not change the hotkey for zotero-tag again.
