### ISSUE TITLE
Adding in actions list "remove tags when creating annotation or note"

### ISSUE THREAD

**Issue by dcfvg** [windingwind/zotero-tag#64]
Thanks a lot for your marvellous work, I'm so thankful this extension exists! 

A small detail to make it perfect. 
In the action list of the rules pan , I would love two more options :  

- **remove** tags when creating annotation
- **remove** tags when creating note 

Is there any plan to add these? 

D

**Comment by coralpereda** [comment]
Hi! 
have you tried using the ~~ notation in  the 'tag' column like this?
`~~mytag` and then in 'actions' maybe select one of the annotations options
