### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by bmatthiss** [windingwind/zotero-tag#67]
First, Thank you for this wonderful tool, it really helps to organize tags.
Am I right that it is not possible right now to import a CSV file with the same format provided with your own csv-export feature (TAG,COUNT,ITEMS,IDS)?
If yes, would it be possible to extend the CSV import feature in that way? 
This would allow managing tags with a spreadsheet program, a clear benefit for large libraries.

Thanks in advance!

**Comment by windingwind** [comment]
There are detailed explanations for the import CSV function. It does not use the same format as the exported CSV. The main purpose is to add/remove/replace tags in batch, not assign different tags for different items.

Hope this helps you understand how it works. And happy Chinese lunar new year.

**Comment by RuizSerra** [comment]
I second this! It would be amazing to be able to clean up tags this way. For example:

1. Export entire library using Zotero-tag
2. Replace all tags e.g. "Machine Learning" with "machine-learning"
3. Import entire library in the same format as export, and it replaces the tags in the relevant items

**Comment by aquaresima** [comment]
Yes please! 
Also, currently, the CSV created by 'export-tag' is pretty unusable. 
The TAG,COUNT,ITEMS,IDS are coma separated. But so are the title and IDS themselves.
This is an example of one line of that CSV:
'''
Selective persistent activity, #(TAG)
8, #(COUNT)
"Neuronal networks for induced '40 hz' rhythms,On the use of computation in modelling behaviour,Chapter 7 - Analog and Digital Processing in Single Nerve Cells: Dendritic Integration and Axonal Propagation,Model of global spontaneous activity and local structured activity during delay periods in the cerebral cortex,The Hebbian paradigm reintegrated: Local reverberations as internal representations,Redistribution of synaptic efficacy between neocortical pyramidal neurons,Chaos in neuronal networks with balanced excitatory and inhibitory activity,Correlations of cortical Hebbian reverberations: theory versus experiment",#(ITEMS)
"40,41,42,44,46,47,45,43" #IDS
'''

The new-line was inserted by my for readability, but obviously this is a single line. 
I could not find any way to set the delimiter such that the line was parsed correctly in the 4 fields.

Please add a special character, or better, a combination, like ";\t" such that it can be easily parsed by setting ";\n" as the delimiter in the CSV.read(...)

Thanks!
