### ISSUE TITLE
Rules for color tags

### ISSUE THREAD

**Issue by coralpereda** [windingwind/zotero-tag#68]
Hi! Thank you for a great plug-in! 
Is there a way to create a rule that assigns a tag if an existing tag has a particular color?

for example instead of assigning the tag `fruits` if the tag `apple` exists by doing `'fruits[apple]'`, is there a way to assign `fruits` if an existing tag is colored red?

**Comment by windingwind** [comment]
Sorry this is not implemented.

In Zotero, tag-color is one on one. It seems to be nonsense to use color instead of tag in conditions.
