### ISSUE TITLE
Auto tag and auto read do not work when drag pdf into zotero

### ISSUE THREAD

**Issue by GFDGIT** [windingwind/zotero-tag#7]
When drag pdf into zotero which has installed Jasminum, zotero-tag popup and prompt add `autotag` to item, but it actually didn't, there is nothing in the tag tab. When I press `Alt+0`, it worked as expected.

**Comment by GFDGIT** [comment]
When add new item through zotero-connector , it works well.

**Comment by windingwind** [comment]
Could you please report this to Jasminum? I'm not pretty sure what's going on inside it that prevents the zotero-tag auto tagging.

**Comment by GFDGIT** [comment]
> Could you please report this to Jasminum? I'm not pretty sure what's going on inside it that prevents the zotero-tag auto tagging.

OK.
I also try drag English pdf into zotero, it works normally, so the problem may be caused by Jasminum.
