### ISSUE TITLE
无法添加标签

### ISSUE THREAD

**Issue by yrg974** [windingwind/zotero-tag#70]
1.目前在首选项中显示如下，和别人的不太一样
![图片](https://user-images.githubusercontent.com/124788352/217526220-8ebcec7e-bae4-470f-8612-215101aedd5e.png)
2.新增规则后
![图片](https://user-images.githubusercontent.com/124788352/217526534-7cc5114b-f46f-403b-b8a9-f2d010e412bd.png)
3.点击圈中位置
![图片](https://user-images.githubusercontent.com/124788352/217526793-9c8afd83-9802-48ee-871e-eb4daa457e38.png)
4.会变成如下所示
![图片](https://user-images.githubusercontent.com/124788352/217526931-aa294524-c8ab-4832-9b4e-a931e0ae4cba.png)
5.重复2号操作，然后点击ok，重启zotero，会如下图所示
![图片](https://user-images.githubusercontent.com/124788352/217527331-c5a125a4-8f45-45a7-9dc3-a32d8d332923.png)
我下载zotero-tag的第一天是正常的，第二天就变成了现在的样子。这是什么问题呀，有什么解决方法吗，谢谢~

**Comment by windingwind** [comment]
1. 请更新插件
2. 可能是if插件冲突，见先前issue

**Comment by yrg974** [comment]
感谢，确实是这样的！remove了zetero if之后就恢复正常了
![图片](https://user-images.githubusercontent.com/124788352/217695890-16550011-b420-4d30-868f-5252daa3307f.png)

**Comment by yrg974** [comment]
非常感谢~
