### ISSUE TITLE
使用 zotero connector 插件保存论文时 闪退

### ISSUE THREAD

**Issue by merak0514** [windingwind/zotero-tag#73]
今天更新完 zotero 之后出现此问题。 mac 系统，点击zotero connector 后 zotero 出现条目，但是在出现 pdf 之前闪退。

**Comment by Goodyzhang** [comment]
我也

**Comment by windingwind** [comment]
请确认是否和本插件有关

**Comment by Goodyzhang** [comment]
已解决，sci-hub plugins for zotero插件与其它插件冲突



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: windingwind ***@***.***&gt;
发送时间: 2023年4月13日 12:53
收件人: windingwind/zotero-tag ***@***.***&gt;
抄送: Goodyzhang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [windingwind/zotero-tag] 使用 zotero connector 插件保存论文时 闪退 (Issue #73)





 
请确认是否和本插件有关
