### ISSUE TITLE
右击标签没有Assign Color项

### ISSUE THREAD

**Issue by Makohhh** [windingwind/zotero-tag#74]
![1678073141366](https://user-images.githubusercontent.com/106016300/223012910-c5eb03d4-a2cb-43a4-9929-e2c0b133d4e7.png)
如图，右击标签没有Assign Color选项
另外，添加了⭐标签也没有显示在条目前
![image](https://user-images.githubusercontent.com/106016300/223013435-6fc405fe-aa01-41c2-89f7-72c710424295.png)

**Comment by ShuaiXuan** [comment]
我有同样的问题，请问你是如何解决的
