### ISSUE TITLE
笔记自动添加标签后不显示

### ISSUE THREAD

**Issue by zhengchuchuan** [windingwind/zotero-tag#75]
使用add tags when creating note/annotation时,在pdf阅读时添加笔记会自动给笔记添加标签,并且主视图的标签栏筛选添加的标签可以找到刚刚添加标签的文献,但是在该文献条目下不会显示添加的标签

**Comment by menmeng-wong** [comment]
我也是，显示skipping tag
![image](https://user-images.githubusercontent.com/128115110/225807622-a81150b3-b1d5-4f01-bb34-334b65219c94.png)

**Comment by laserchaosrelay** [comment]
Me too
