### ISSUE TITLE
Expect some actions detecting the item notes

### ISSUE THREAD

**Issue by Jensen-Inequality** [windingwind/zotero-tag#76]
Thank you for your marvellous contribution to zotero add-ons!
It improves my working efficiency greatly.

I notice that there are some actions about creating notes and annotations.
I think they are actions directly related to PDF.
**It seems that there are no actions directly related to the notes about the whole item.**

I usually make some notes for summary after I read some papers.
Therefore, if zotero-tag can detect the creation of notes under the item, `/read` tags can be added to items automatically.

Best regards.

**Comment by windingwind** [comment]
I’m not sure if it’s a common use case. You could start a voting about this feature.

**Comment by andreifoldes** [comment]
This is something I was also thinking of today. 
There is an "add tag when creating annotations" / "add tag when creating note" action in the plugin, but I find that they both execute when I annotate pdfs... Would be nice to have a tag that only runs when "better note note is created".
