### ISSUE TITLE
为什么在标签里面添加⭐之后，除了一颗星的标记可以显示在文献前面，两颗星，三颗星等都不能显示在文献前面

### ISSUE THREAD

**Issue by luckboyya** [windingwind/zotero-tag#78]
![image](https://user-images.githubusercontent.com/127922414/227719905-cb2feedd-ff55-4b83-8b1e-cddb8efc1449.png)

**Comment by meflm** [comment]
我的全部不显示，奇怪

**Comment by Springder** [comment]
我能显示1颗星和3颗星
