### ISSUE TITLE
Windows11使用zotero-tag在设置规则时，动作栏只有打勾的选项，没有add on item add这些规则

### ISSUE THREAD

**Issue by PawnYoung** [windingwind/zotero-tag#79]

**Comment by zkyling** [comment]
![image](https://user-images.githubusercontent.com/129839916/229734497-8adbedd7-a343-4397-a090-09ffd35fed2a.png)
相同的问题，希望得到帮助！谢谢！

**Comment by mifa1031** [comment]
你解决这个问题了吗，我也出现了

**Comment by zkyling** [comment]
您好，之前忘记回复了，我还没有解决，请问您在现在解决了吗？
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月19日 17:27 |
| 收件人 | windingwind/zotero-tag ***@***.***> |
| 抄送人 | zkyling ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [windingwind/zotero-tag] Windows11使用zotero-tag在设置规则时，动作栏只有打勾的选项，没有add on item add这些规则 (Issue #79) |

你解决这个问题了吗，我也出现了
