### ISSUE TITLE
Add a reading status ( for longer articles or books ) ?

### ISSUE THREAD

**Issue by GFDGIT** [windingwind/zotero-tag#8]
At present, I have implemented the reading tag through the settings shown in the figure below.
![image](https://user-images.githubusercontent.com/22742500/161362971-9d1d9702-e600-46a3-89a6-e721f9e28841.png)
🔔 for /unread, ⏳ for /reading, ✔️ for read. 

And I set ⏳ and ✔️ the same shortcut, so ⏳ and ✔️ will not show at the same time. But 🔔 and ⏳ will add to new item together.

Can add an /reading tag which add to item when first open the pdf, and then remove the /unread tag? Then when press the shorcut of /read tag, remove the /reading tag.

**Comment by windingwind** [comment]
Thanks for your suggestion. I'll work on that.

**Comment by windingwind** [comment]
@GFDGIT v0.2.0 provides more actions that can trigger the *auto tag/untag*. 
1. Set a rule: `unread` to *add on item add*, press ✅
2. Set a new rule: `unread` to *remove on item open*, press ✅
3. Set a new rule: `reading` to *add on item open*, press ✅
4. Set a new rule: `read` to *disabled*, choose a shortcut, then press ✅

**Comment by GFDGIT** [comment]
☆⌒(*＾-゜)v THX!!
