### ISSUE TITLE
[Feature Request] Add Tags conditional on Field

### ISSUE THREAD

**Issue by marcelowoo** [windingwind/zotero-tag#85]
Hi!

First of all, thank you for this amazing plugin! 

I would like to request a feature:

- Use case: I have a big list of papers to read, and I would like to have a quick marker of the importance of the paper to prioritize my reading time. In some fields, there is a ranking of journals, which is an indication of the general quality of the paper belonging to that journal. I would like to select a subset of journals (perhaps manually), and based on that, get the papers from those journals tagged with a "Top journal" tag. This allows me to quickly identify which papers are important readings, and to stay on top of the evolving literature.

- Current method: go to My Library → Sort by "Publication" field → Find matches based on journal → Manually add "Top journal" tag. (Painful!)

- Proposed solution: allow Zotero Tag plugin to set rules based on content of fields, such as "Publication" field. For example, if "Publication" contains "X", "Y", or "Z" journals, add the "Top journal" tag.

- Other possible use cases: tags based on authors, words in title, keywords.

I think this would be an amazing use case and feature of the Zotero Tag!

In any case, thanks a lot for this wonderful plugin!

**Comment by RRTogunov** [comment]
Just wanted to note that this issue is a generalisation of [this issue](
https://github.com/windingwind/zotero-tag/issues/77#issue-1635804932) for automatically generating tags based on a keyword in the title. The only additional layer is searching for string within in a field.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/discussions/119
