### ISSUE TITLE
Do you have any plans to be compatible with zotero 7?

### ISSUE THREAD

**Issue by BenjaminDbb** [windingwind/zotero-tag#88]
Obviously, this plugin is currently not compatible with Zotero 7. 
I am wondering if there are any plans to update it for compatibility?

**Comment by windingwind** [comment]
On the way but a little bit behind schedule.

**Comment by sheldon123z** [comment]
> On the way but a little bit behind schedule.
加油加油，等待你的作品，这个标签插件一直在用，是 zotero 最好用的插件之一
