### ISSUE TITLE
新版的标签颜色为什么不显示了？

### ISSUE THREAD

**Issue by XyhL** [windingwind/zotero-tag#89]
之前使用的emoji表情作为标志，但是更新以后，所有的emoji颜色全部丢失，变成了黑白色。

> 
![1686642943882](https://github.com/windingwind/zotero-tag/assets/46349473/39bacfd6-01b9-4549-aefc-3a65f5d9b0aa)

**Comment by QingYu-sunshine** [comment]
我的也是，突然就变得没有颜色了，但是我看了一下最近的一次更新明明是去年啊

**Comment by jinaoao** [comment]
我也遇到这个问题了，不知道咋回事，重装了zotero也没有用，换了7版本也有问题

**Comment by XyhL** [comment]
@jinaoao 我是换了7，然后重新配置了一下，才可以的。emoji用的是”https://emoji6.com/emojiall/“。

**Comment by jinaoao** [comment]
> @jinaoao 我是换了7，然后重新配置了一下，才可以的。emoji用的是https://emoji6.com/emojiall/

我同实验室的也出现了这个问题，应该windows11 9月份的更新的导致的问题，我今天试过了重新安装了zotero7，还是有一样的问题，emoji显示不正确

**Comment by XyhL** [comment]
> > @jinaoao 我是换了7，然后重新配置了一下，才可以的。emoji用的是https://emoji6.com/emojiall/
> 
> 我同实验室的也出现了这个问题，应该windows11 9月份的更新的导致的问题，我今天试过了重新安装了zotero7，还是有一样的问题，emoji显示不正确

我是在主页的信息找了一个输入框，粘贴emoji显示正常，只是tags显示不正常，所以我就升级版本，然后重新安装了版本为1.0.0-15的插件。

**Comment by jinaoao** [comment]
> > > @jinaoao 我是换了7，然后重新配置了一下，才可以的。emoji用的是https://emoji6.com/emojiall/
> > 
> > 
> > 我同实验室的也出现了这个问题，应该windows11 9月份的更新的导致的问题，我今天试过了重新安装了zotero7，还是有一样的问题，emoji显示不正确
> 
> 我是在主页的信息找了一个输入框，粘贴emoji显示正常，只是tags显示不正常，所以我就升级版本，然后重新安装了版本为1.0.0-15的插件。

我在zotero页面粘贴emoji显示不正常的，tag也显示不正常，和插件没有关系。我和我实验室另外一个同学有一样的问题，应该就是windows11 9月份的更新导致的，没有安装这个更新的同学的电脑上的zotero是正常的

**Comment by jinaoao** [comment]
> > > @jinaoao 我是换了7，然后重新配置了一下，才可以的。emoji用的是https://emoji6.com/emojiall/
> > 
> > 
> > 我同实验室的也出现了这个问题，应该windows11 9月份的更新的导致的问题，我今天试过了重新安装了zotero7，还是有一样的问题，emoji显示不正确
> 
> 我是在主页的信息找了一个输入框，粘贴emoji显示正常，只是tags显示不正常，所以我就升级版本，然后重新安装了版本为1.0.0-15的插件。

我下午安装了zotero7体验了一下，标签虽然显示不正确，但是有颜色，可以分辨出来，但是我安装的插件中，style和better bibtex这两个有问题，使用style设置pdf背景颜色的时候，显示也是不正确的，better bibtex的问题就是，有一些文章在info的面板上不显示citekey，有一些会显示，我不知道是我的设置问题还是插件或者zotero7 beta本身的bug
