### ISSUE TITLE
Rarely used tag popup window disappears 

### ISSUE THREAD

**Issue by notuntoward** [windingwind/zotero-tag#96]
When I try to remove rarely used tags by clicking the `Rarely-Used Tags` button (screenshot 1), a 2nd popup is made  where I can enter the tag count to remove (screenshot 2).  The problem is that the 2nd popup immediately disappears behind the zotero window, where there is no way I can access it.

This is on Windows 11, with the [Enable Window Tracking](https://winaero.com/app-launch-tracking-windows-10/) activation time set to 500 ms.  With this setting, the the 2nd popup appears, and then immediately, the main zotero window is raised above it.

Would it be possible to merge the 1st and 2nd popups, so there is only one of them, and this problem goes away?

<img width="502" alt="image" src="https://github.com/windingwind/zotero-tag/assets/3851891/f3ca9c25-0fe8-4824-833a-a0e4a756895b">
<img width="274" alt="image" src="https://github.com/windingwind/zotero-tag/assets/3851891/81d7ad3b-9da6-4d2e-a4a9-9db5a4ddb666">

**Comment by bczucz** [comment]
I have exactly the same issue, the second popup is disappearing right behind the main zotero window, and it only becomes visible when I have pressed "cancel" on the first popup. 
I can see that you marked this issue completed... but what was the solution? Should I install a dev version of the xpi? (Thanks for any helpful hint... I am totally stuck.)

**Comment by notuntoward** [comment]
Are you removing the ability to find and remove rarely used tags, or just the popup?  I have to say that I liked the rarely used tag feature.

**Comment by windingwind** [comment]
Both. The plugin is redesigned to be more flexible and support more customizable operations, including these features. They should be an action script instead of a builtin feature.
